# Generated by Django 4.2.1 on 2023-05-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Название')),
                ('category_desc', models.CharField(max_length=100, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Название')),
                ('product_desc', models.CharField(max_length=1000, verbose_name='Описание')),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('product_cat', models.CharField(max_length=100, verbose_name='Категория')),
                ('product_price', models.IntegerField(verbose_name='Цена')),
                ('product_mk', models.CharField(max_length=100, verbose_name='Дата создания')),
                ('product_ed', models.CharField(max_length=100, verbose_name='Дата изменения')),
            ],
        ),
    ]
