# Generated by Django 4.2.1 on 2023-05-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукты'},
        ),
    ]
