# Generated by Django 4.2.1 on 2023-05-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Продукты'},
        ),
    ]
