# Generated by Django 4.2.1 on 2023-05-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_project', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'Категории'},
        ),
    ]
